// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"20","screenWidth":"512","screenHeight":"448","changeWindowWidthTo":"512","changeWindowHeightTo":"448","renderingMode":"webgl","alwaysDash":"off"}},
{"name":"Yami_SkipTitle","status":true,"description":"テストプレイ用にタイトルシーンを飛ばすことができます。","parameters":{}},
{"name":"DisableFastForward","status":true,"description":"イベント高速化禁止プラグイン","parameters":{}},
{"name":"BugFixWebPlayTest","status":true,"description":"Web実行のテストプレー防止プラグイン","parameters":{}},
{"name":"BugFixImageOnLoad","status":true,"description":"画像ロード遅延時のエラー修正プラグイン","parameters":{}},
{"name":"PictureAnimation","status":true,"description":"ピクチャのアニメーションプラグイン","parameters":{"最初のセルに戻る":"false"}}
];
